### ISSUE TITLE
Code Error: 

### ISSUE THREAD

**Issue by Dev-Larks** [devblackops/building-powershell-modules-feedback#25] opened 2020-07-01 06:01 UTC
## Description

When using the build.ps1 script from section 9.4.2.1 Creating an output directory

I'm getting errors saying that the .ps1 files in the $sourceFiles variable cannot be found as the paths it is using are incorrect.

## Chapter/section/subsection

- Chapter: 9
- Section: 4
- Subsection: 2.1

## Current behavior

PS C:\DEV\AcmeEmployee> .\build.ps1

Get-Content : Cannot find path 'C:\DEV\AcmeEmployee\Initialise.ps1' because it does not exist.
At C:\DEV\AcmeEmployee\build.ps1:25 char:5
+     Get-Content $_
+     ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\DEV\AcmeEmployee\Initialise.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

## Expected behavior

These .ps1 files are supposed to be found in the next directory down, but the paths are incorrect. 
The contents of each .ps1 file is then taken and placed in the .psm1 file in the Output directory

## Screenshots

Build_001 - values in $sourceFiles variable
Build_002 - error messages when content of individual .ps1 files are attempted to be added to Output .psm1 file
Build_003 - current module structure
Build_004 - Output folder .psm1 file content
Build_005 - Actual content of build.ps1 file
![Build_001](https://user-images.githubusercontent.com/44560717/86207912-e3e17d80-bbb2-11ea-8a2f-6c65441f1328.PNG)
![Build_002](https://user-images.githubusercontent.com/44560717/86207926-e643d780-bbb2-11ea-83ad-2b37c915c767.PNG)
![Build_003](https://user-images.githubusercontent.com/44560717/86207929-e7750480-bbb2-11ea-968b-7f22e56ba474.PNG)
![Build_004](https://user-images.githubusercontent.com/44560717/86208184-679b6a00-bbb3-11ea-88c8-372ba5a540b3.PNG)
![Build_005](https://user-images.githubusercontent.com/44560717/86208368-c365f300-bbb3-11ea-904b-08604d2cd58b.PNG)

**Comment by clee1107** [comment] 2020-07-01 17:09
Seeing same issue.

Can clear errors by adding sub module name 

`$sourceFiles = Get-ChildItem -Path ./AcmeEmployee/AcmeEmployee -Filter '*.ps1' -Recurse`

But then no .psm1 file is created in Output

Was able to get code to copy by making following adjustment:

`$sourceFiles | ForEach-Object {
            "# source: $($_.Name)"
            Get-Content "$($_.Directory)\$($_.Name)"
            ''
        } | Add-Content -Path $rootModule -Encoding utf8`

**Comment by devblackops** [comment] 2020-07-01 17:15
Doh! Thanks for finding this! Fix will be incoming.

**Comment by devblackops** [comment] 2020-07-02 23:23
Thanks for reporting this. Are you using Windows PowerShell? This looks like broken behavior in Windows PowerShell that has since been fixed in PowerShell Core.

The problem is with `Get-Content $_`. That fails in Windows PowerShell but not PowerShell Core.

Try changing it to:
```powershell
Get-Content -Path $_.FullName
```

OR

```powershell
$_ | Get-Content
```

Sorry for the bug! The text has been updated and will be in the next update.

**Closed as completed by devblackops** 2020-07-02 23:23 UTC
Labels: code error

**Comment by Dev-Larks** [comment] 2020-07-03 06:30
Hi Brandon

I was using PowerShell 5.1 as I was doing this on my work laptop.

I’ll check your solution and confirm early next week if the issue is no longer occurring.

Cheers Craig

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Dev-Larks** [comment] 2020-07-06 03:30
Hi Brandon

Had a chance to test today, confirming the expected behaviour when running the .\build.ps1 file is now occurring using either of the two solutions you provided.

Regards

Craig

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Craig Larkin<mailto:Dev_Larks@outlook.com>
Sent: Friday, 3 July 2020 4:30 PM
To: devblackops/building-powershell-modules-feedback<mailto:reply@reply.github.com>
Subject: RE: [devblackops/building-powershell-modules-feedback] Code Error: (#25)

Hi Brandon

I was using PowerShell 5.1 as I was doing this on my work laptop.

I’ll check your solution and confirm early next week if the issue is no longer occurring.

Cheers Craig

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by devblackops** [comment] 2020-07-06 05:29
Thanks for checking back @Dev-Larks 👍
